### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by Thoth1111** [Thoth1111/Rails-Group-Capstone#11]
Here is a link to the project: 
https://github.com/users/Thoth1111/projects/3/views/1

We are two people in our group.

**Comment by bobb-Rob** [comment]
## STATUS: CHANGES REQUIRED ♻️
Hi Team, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️

Well done for setting this kanban board very well, except that a few issues needs to be worked on 👇🏾 

- [ ] You have only three columns _**Todo**_, _**In progress**_, and _**Done**_ where as there should be four columns in this order 👉🏾 _**Todo**_, _**In progress**_, _**In review**_  and _**Done**_ . Kindly add an **In review** column. Then ask for another review. 


Cheers and Happy coding!👏👏👏

**Comment by levy002** [comment]
### Hello @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
